project:
  type: website

website:
  page-navigation: true
  title: "Grant"

  page-footer:
    left: "&copy; Copyright 2024, Grant Bruer"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Projects"
        href: projects/index.qmd

      - text: "Talks"
        href: talks/index.qmd

      - text: "Blog"
        href: blog.qmd

      - section: "About"
        contents:
          - text: "About me"
            href: about.qmd
          - text: "This template"
            href: about_template.qmd
  reader-mode: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
